### ISSUE TITLE
Comment configurer l'app pour commencer à travailler dessus ?

### ISSUE THREAD

**Issue by Em-AK** [simplonco/robespierre#7]
Votre README est pas très clair. Voilà ce que j'ai fait:
- bundle install
- création du fichier .env

```
CONSUMER_KEY='Mon API key'
CONSUMER_SECRET='mon API secret'
ACCESS_TOKEN='mon access token (read-only)'
ACCESS_TOKEN_SECRET='mon access token secret'
```
-  `$ shotgun twitter-stream.rb`

J'obtiens un joli 

"Boot Error"
Something went wrong while loading twitter-stream.rb
EOFError: end of file reached

```
Listening on 127.0.0.1:9393, CTRL+C to stop
{:status_code=>401, :header=>{"WWW-Authenticate"=>"OAuth realm=\"Firehose\"", "Content-Type"=>"text/html", "Cache-Control"=>"must-revalidate,no-cache,no-store", "Transfer-Encoding"=>"chunked"}}

```

**Comment by theFreedomBanana** [comment]
Il faut que tu fork la branch benja, la branch master n'a plus rien à voir avec le projet.
Tu rajoute un fichier .env à la racine et tu y mets : 
CONSUMER_KEY='Mon API key'
CONSUMER_SECRET='mon API secret'
ACCESS_TOKEN='mon access token (read-only)'
ACCESS_TOKEN_SECRET='mon access token secret'

Tu remplaces ce qu'il y a entre les quotes par des tokens twitter. Tu peux t'en créer sur twitter dans => Paramètres/Développeurs puis en haut à droite sur ta profil picture My applications/create new app

Normalement avec ça ça marche.
Dis moi sur quoi tu pars. Je suis sur le player pour ma part et Alix sur le système de vote.
Si tu rencontres d'autres problèmes ou si tu as des questions n'hésites pas. Merci

**Comment by theFreedomBanana** [comment]
PS: pas besoin d' un bundle install, il n'y a pas de gemfile les dépendances sont required dans l'app.rb

**Comment by klacointe** [comment]
L'utilisation de bundler est fortement recommandé pour des projets Ruby, notamment pour la gestion des dépendances mais aussi pour la simplicité d'installation de l'application.
